apiVersion: v2
name: ssl-storage
description: Helm chart for deploying the SSL Storage ACME/Let's Encrypt certificate manager service
type: application
version: 0.1.1
appVersion: "0.0.1"
keywords:
  - ssl
  - certificates
  - acme
  - letsencrypt
sources:
  - https://github.com/gen0sec/ssl-storage
maintainers:
  - name: Gen0Sec
    email: support@gen0sec.com
