apiVersion: v2
name: synapse-operator
description: Helm chart for the Synapse Kubernetes operator
# Release synapse-operator v1.0.0
type: application
version: 1.1.0
appVersion: "0.1.2"
home: https://gen0sec.com
icon: https://raw.githubusercontent.com/gen0sec/helm-charts/main/images/logo.png
sources:
  - https://github.com/gen0sec/synapse-operator
keywords:
  - synapse
  - operator
  - kubernetes
  - security
maintainers:
  - name: Gen0Sec
    email: support@gen0sec.com
